version: '2.23.3'

services:
  web:
    build: ./back_end
    volumes:
      - ./back_end:/app
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
      - PORT=5000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_DB=cosmos
      - POSTGRES_URL=db:5432
      - SECRET_KEY=frittoMistico4ever
    depends_on:
      - db
  db:
    image: postgres:16
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_DB=cosmos
