version: '2.23.3'

services:
  web:
    build: ./back_end
    volumes:
      - .back_end:app
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
      - PORT=5000
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - POSTGRES_URL= 
  db:
    image: postgres:16
    expose:
    - "5432"
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

